export const PENGAJUAN_STATUS = Object.freeze({
  DIAJUKAN: "DIAJUKAN",
  DALAM_PEMERIKSAAN: "DALAM_PEMERIKSAAN",
  PERLU_KLARIFIKASI: "PERLU_KLARIFIKASI",
  DISETUJUI: "DISETUJUI",
  DITOLAK: "DITOLAK",
  SELESAI: "SELESAI",
});

export const PENGAJUAN_STATUS_LIST = Object.freeze(
  Object.values(PENGAJUAN_STATUS),
);

export const PENGAJUAN_ALLOWED_TRANSITIONS = Object.freeze({
  [PENGAJUAN_STATUS.DIAJUKAN]: [
    PENGAJUAN_STATUS.DALAM_PEMERIKSAAN,
    PENGAJUAN_STATUS.DITOLAK,
  ],
  [PENGAJUAN_STATUS.DALAM_PEMERIKSAAN]: [
    PENGAJUAN_STATUS.PERLU_KLARIFIKASI,
    PENGAJUAN_STATUS.DISETUJUI,
    PENGAJUAN_STATUS.DITOLAK,
  ],
  [PENGAJUAN_STATUS.PERLU_KLARIFIKASI]: [
    PENGAJUAN_STATUS.DIAJUKAN,
    PENGAJUAN_STATUS.DITOLAK,
  ],
  [PENGAJUAN_STATUS.DISETUJUI]: [PENGAJUAN_STATUS.SELESAI],
  [PENGAJUAN_STATUS.DITOLAK]: [],
  [PENGAJUAN_STATUS.SELESAI]: [],
});